#!/usr/bin/env python3
"""
SCOPE v0.2 — candidate prediction target analysis (Phase 1 exploration).

This script explores what the dataset explicitly provides that could serve
as an activity-level delay target, and what would need to be derived.

IMPORTANT:
- Do NOT treat this as final target selection.
- This is one input to a human decision (Phase 1 → Phase 3.5).
"""
import csv, collections, os

ROOT = "AI-Construction-Project-Risk-Delay-Predictor/data/raw/SCOPE_v02_Public"

def read_csv(name):
    with open(os.path.join(ROOT, f"{name}.csv"), newline="", encoding="utf-8") as f:
        r = csv.reader(f)
        h = next(r)
        return h, [dict(zip(h, row)) for row in r]

def main():
    print("SCOPE v0.2 — Candidate Delay Target Analysis")
    print("="*72)

    _, activities = read_csv("activities")
    _, deps = read_csv("dependencies")
    _, events = read_csv("events")
    _, decisions = read_csv("decisions")
    _, outcomes = read_csv("outcomes")
    _, master = read_csv("master_projects_canonical")
    _, proj = read_csv("projects")
    _, states = read_csv("activity_states")
    _, proc = read_csv("procurement")
    _, cmem = read_csv("construction_memory")

    act_by_proj = collections.defaultdict(list)
    for a in activities:
        act_by_proj[a["project_id"]].append(a)

    print()
    print("1. ACTIVITY-LEVEL: what does the dataset explicitly state about delay?")
    print("-"*72)
    print("  activities.csv has NO explicit 'actual_duration' or 'delay_days' field.")
    print("  It has:")
    print("    - planned_duration_days (int)")
    print("    - status = 'Planned' for ALL 9279 activities (no In-Progress/Completed)")
    print("    - criticality (float)")
    print("    - critical_path (0/1 flag)")
    print("    - critical_path_position (int; -1 for non-critical, 1..30 for critical)")
    print("    - project_network_duration (int; same for all activities in a project)")
    print("    - predecessor_count, successor_count (int)")
    print()
    print("  Implication: activities.csv alone does NOT provide observed delay.")
    print("  Any activity delay target must come from elsewhere or be derived.")

    print()
    print("2. EVENT-LEVEL: what does events.csv provide?")
    print("-"*72)
    print(f"  Total events: {len(events)}")
    print(f"  event_type values: {sorted(set(e['event_type'] for e in events))}")
    print(f"  severity values: {sorted(set(e['severity'] for e in events))}")
    print(f"  duration_days: min={min(int(e['duration_days']) for e in events)} "
          f"max={max(int(e['duration_days']) for e in events)}")
    print(f"  impact_factor: min={min(float(e['impact_factor']) for e in events):.3f} "
          f"max={max(float(e['impact_factor']) for e in events):.3f}")
    print(f"  cause_node values: {sorted(set(e['cause_node'] for e in events))}")
    print()
    print("  Each event is linked to a single activity_id and has a date, type,")
    print("  severity, duration_days, cause_node, impact_factor.")
    print("  So event-level 'disruption duration' is available (duration_days).")
    print("  But events are NOT the same as activity delay — an event is one")
    print("  possible contributor to an activity being delayed.")

    print()
    print("3. DECISION-LEVEL: what does decisions.csv provide?")
    print("-"*72)
    print(f"  Total decisions: {len(decisions)}")
    print(f"  decision_status: {collections.Counter(d['decision_status'] for d in decisions)}")
    print(f"  decision_delay_days: min={min(int(d['decision_delay_days']) for d in decisions)} "
          f"max={max(int(d['decision_delay_days']) for d in decisions)}")
    print(f"  decision_debt_level: {collections.Counter(d['decision_debt_level'] for d in decisions)}")
    print(f"  decision_type values: {sorted(set(d['decision_type'] for d in decisions))}")
    print()
    print("  Each decision is linked to an activity_id and has:")
    print("    - required_day (int)")
    print("    - actual_decision_day (int)")
    print("    - decision_delay_days = actual - required (int)")
    print("  So there IS an explicit decision delay concept at activity level.")
    print("  IMPORTANT: a delayed decision != a delayed activity; but decisions are")
    print("  associated with activities and could be a feature or a proxy target.")
    print()
    print("  Question for human: do we want to predict:")
    print("    (a) activity delay (activity itself runs late)?")
    print("    (b) decision delay (a management decision for an activity is late)?")
    print("    (c) both? These are different targets with different meanings.")

    print()
    print("4. CONSTRUCTION_MEMORY: what does it provide re: observed delay?")
    print("-"*72)
    print(f"  Total memory records: {len(cmem)}")
    print(f"  memory_type: {collections.Counter(r['memory_type'] for r in cmem)}")
    obs_delay = [float(r['observed_delay_days']) for r in cmem if r['observed_delay_days']]
    obs_rework = [float(r['observed_rework_days']) for r in cmem if r['observed_rework_days']]
    if obs_delay:
        print(f"  observed_delay_days: min={min(obs_delay)} max={max(obs_delay)} "
              f"n_nonempty={len(obs_delay)}")
    if obs_rework:
        print(f"  observed_rework_days: min={min(obs_rework)} max={max(obs_rework)} "
              f"n_nonempty={len(obs_rework)}")
    print(f"  failure_flag: {collections.Counter(r['failure_flag'] for r in cmem)}")
    print()
    print("  IMPORTANT: construction_memory contains observed_delay_days and")
    print("  observed_rework_days, but it is a derived/experience representation,")
    print("  not raw activity outcomes. It also has missing fields (event_type,")
    print("  decision_type, resource_type, phase, activity_name).")
    print("  Its memory_type includes 'activity_pattern', 'risk_pattern', etc.")
    print()
    print("  Question for human: is construction_memory the intended source of")
    print("  the ground-truth delay target? Or is it an auxiliary feature source?")
    print("  Need to understand how memory records map to activities (1:1? many:1?).")

    print()
    print("5. PROJECT-LEVEL OUTCOMES: what is available at project level?")
    print("-"*72)
    print(f"  outcomes.csv has per project:")
    print(f"    - total_activities (int)")
    print(f"    - total_planned_duration (int)")
    print(f"    - split")
    print()
    print(f"  master_projects_canonical.csv has per project (29 columns):")
    mcols = list(master[0].keys())
    for c in mcols:
        print(f"    - {c}")
    print()
    print("  master_projects_canonical appears to aggregate:")
    print("    - activity counts, planned duration")
    print("    - risk event counts (total_risk_events, high_critical_events, total_event_delay)")
    print("    - decision counts (total_decisions, delayed_decisions, total_decision_delay)")
    print("    - decision debt (total_decision_debt, maximum_decision_debt)")
    print("    - friction (total_friction_hours, friction_event_count, mean/max severity,")
    print("      construction_friction_index)")
    print()
    print("  NOTE: At project level, there is NO explicit 'actual project completion date'")
    print("  or 'project delay days' field. total_planned_duration is the planned")
    print("  project duration (same value as project_network_duration in activities).")
    print()
    print("  Question for human: what is the project-level delay target?")
    print("    - Is it derived from activity states over time?")
    print("    - Is it derived from some schedule simulation not in the raw data?")
    print("    - Or is the project target ONLY observable via construction_memory /")
    print("      counterfactuals at the event level?")

    print()
    print("6. ACTIVITY_STATES: what does the time-series provide?")
    print("-"*72)
    print(f"  Total state observations: {len(states)}")
    print(f"  Fields: project_id, activity_id, date, day_index,")
    print(f"          productivity_index, weather_risk, site_access_index, event_pressure, split")
    print(f"  date range: {min(s['date'] for s in states)} .. {max(s['date'] for s in states)}")
    print(f"  day_index range: {min(int(s['day_index']) for s in states)} .. {max(int(s['day_index']) for s in states)}")
    prod = [float(s['productivity_index']) for s in states]
    evpress = [float(s['event_pressure']) for s in states]
    print(f"  productivity_index: min={min(prod):.3f} max={max(prod):.3f}")
    print(f"  event_pressure: min={min(evpress):.3f} max={max(evpress):.3f}")
    print()
    print("  These are SNAPSHOT time-series, not event logs. They give daily")
    print("  operating conditions per activity, but NOT start/completion timestamps.")
    print("  NOTE: activity_states does NOT directly tell us when an activity started")
    print("  or finished. It gives state values on each day for each activity.")
    print()
    print("  Question for human: Can we derive activity actual start/end from")
    print("  activity_states? E.g., is 'activity present in states for N days' ==")
    print("  'activity lasted N days'? Or do states exist for all days regardless")
    print("  of whether the activity was active? Need to verify temporal coverage")
    print("  per activity (does a completed activity stop appearing? Or does it")
    print("  continue to appear with low productivity?).")

    print()
    print("7. PROCUREMENT: what supply-chain delay info exists?")
    print("-"*72)
    print(f"  Total procurement records: {len(proc)}")
    print(f"  material types: {sorted(set(p['material'] for p in proc))}")
    print(f"  procurement_delay_days: min={min(int(p['procurement_delay_days']) for p in proc)} "
          f"max={max(int(p['procurement_delay_days']) for p in proc)}")
    print(f"  planned_lead_days: min={min(int(p['planned_lead_days']) for p in proc)} "
          f"max={max(int(p['planned_lead_days']) for p in proc)}")
    print(f"  actual_lead_days: min={min(int(p['actual_lead_days']) for p in proc)} "
          f"max={max(int(p['actual_lead_days']) for p in proc)}")
    print(f"  supply_chain_risk: min={min(float(p['supply_chain_risk']) for p in proc):.3f} "
          f"max={max(float(p['supply_chain_risk']) for p in proc):.3f}")
    print()
    print("  Procurement is at project level, linked to materials, not individual")
    print("  activities. But procurement is associated with project_id.")
    print("  Can be joined to activities via project_id (not activity-specific).")

    print()
    print("8. INTERVENTION/COUNTERFACTUAL: what is the 'delay' here?")
    print("-"*72)
    _, interv = read_csv("intervention_options")
    _, cfact = read_csv("counterfactuals")
    print(f"  intervention_options: {len(interv)} records")
    print(f"  counterfactuals: {len(cfact)} records")
    bl = [float(r['baseline_delay_days']) for r in cfact]
    cl = [float(r['counterfactual_delay_days']) for r in cfact]
    av = [float(r['avoided_delay_days']) for r in cfact]
    print(f"  baseline_delay_days: min={min(bl):.3f} max={max(bl):.3f}")
    print(f"  counterfactual_delay_days: min={min(cl):.3f} max={max(cl):.3f}")
    print(f"  avoided_delay_days: min={min(av):.3f} max={max(av):.3f}")
    print(f"  true_effectiveness: min={min(float(r['true_effectiveness']) for r in interv):.3f} "
          f"max={max(float(r['true_effectiveness']) for r in interv):.3f}")
    print()
    print("  IMPORTANT: These are event-specific intervention scenarios with")
    print("  synthetic baseline vs counterfactual delay. They are NOT activity")
    print("  delay records. They model 'what if we apply intervention I to event E'")
    print("  and show avoided_delay_days.")
    print()
    print("  raised: can counterfactuals inform a delay target? They are synthetic")
    print("  intervention outcomes, not raw observed delays. Likely useful for")
    print("  evaluating mitigation (Phase 7), not as a prediction target (Phase 4).")

    print()
    print("9. KEY QUESTIONS FOR HUMAN DECISION (do NOT proceed to Phase 4 until)")
    print("-"*72)
    print("  Q1. What is the PRIMARY prediction target for Phase 4 ML?")
    print("      Options:")
    print("        (a) Activity delay (actual_duration - planned_duration)?")
    print("            -> Is this derivable from activity_states? Need to verify.")
    print("        (b) Activity delayed-or-not binary (status != Planned)?")
    print("            -> Currently ALL activities have status=Planned, so not usable")
    print("               from activities.csv alone.")
    print("        (c) Event occurrence per activity (will an event hit this activity)?")
    print("            -> events.csv provides event_type, severity, duration, impact.")
    print("        (d) Decision delay for an activity?")
    print("            -> decisions.csv provides decision_delay_days.")
    print("        (e) Something derived from construction_memory observed_delay_days?")
    print("            -> Need to verify mapping and missingness.")
    print()
    print("  Q2. What is the PROJECT-level target, if any?")
    print("      - No explicit 'actual project duration' or 'project delay days' found.")
    print("      - Is there an intended target derivable from activity_states or")
    print("        counterfactuals? Or is the project target out of scope for Phase 4?")
    print()
    print("  Q3. How do activity_states dates relate to actual activity execution?")
    print("      - Do states only exist during active execution?")
    print("      - Or do states exist for all planned days regardless?")
    print("      - This determines whether we can derive actual duration from states.")
    print()
    print("  Q4. For counterfactuals/intervention_options, are these intended as")
    print("      training data for a model, OR purely as evaluation/mitigation tooling?")
    print()
    print("  Q5. construction_memory has observed_delay_days and observed_rework_days.")
    print("      Is this intended as the delay ground truth? What is the relationship")
    print("      between memory records and activities (1:1, many:1)?")
    print()
    print("  Q6. Is there a preferred split strategy beyond the provided 70/15/15?")
    print("      The dataset already provides project-level train/val/test split.")
    print("      PHASE 4 should honor this split (per CLAUDE.md rule 8).")
    print()
    print("10. DELAY-RELATED FEATURES THAT ARE EXPLICITLY AVAILABLE")
    print("-"*72)
    print("  At activity level (from activities.csv + dependencies + joins):")
    print("    - planned_duration_days")
    print("    - criticality")
    print("    - critical_path flag")
    print("    - critical_path_position")
    print("    - phase, phase_order, activity_sequence")
    print("    - resource_type")
    print("    - quantity, unit_cost, planned_cost")
    print("    - predecessor_count, successor_count")
    print("    - project_network_duration (project-level constant per activity)")
    print()
    print("  At project level (from projects.csv):")
    print("    - project_type, floors, area_m2")
    print("    - complexity, contractor_capability, resource_availability,")
    print("      management_maturity, weather_exposure, supply_chain_exposure,")
    print("      technology_maturity")
    print("    - planned_duration_days, planned_cost")
    print()
    print("  At activity-state time series level:")
    print("    - productivity_index, weather_risk, site_access_index, event_pressure")
    print("      (aggregated over time could become features)")
    print()
    print("  At event level (joined to activity via activity_id):")
    print("    - event count per activity, event types, severity, duration, impact")
    print()
    print("  At decision level (joined to activity via activity_id):")
    print("    - decision count, decision delay, decision debt, decision types")
    print()
    print("  At procurement level (joined via project_id):")
    print("    - material lead time delays, supply_chain_risk")
    print()
    print("  NOT available directly at activity level:")
    print("    - actual_duration_days")
    print("    - actual_finish_date")
    print("    - activity delay (days late)")
    print("    - binary 'delayed' flag (except maybe via states/event presence)")
    print()
    print("DONE")

if __name__ == "__main__":
    main()
